[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x', 'npm']

[phases.install]
cmds = ['pip install -r requirements.txt', 'cd frontend && npm install']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'python main.py'